// Generates src/tokens/primitives.css and src/tokens/semantic.css from src/tokens/source/*.txt
// Source files mirror the Figma variable collections. Do not hand-edit the generated CSS.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const src = (f) => resolve(root, "src/tokens/source", f);
const out = (f) => resolve(root, "src/tokens", f);

const parse = (file) =>
  readFileSync(src(file), "utf8")
    .split("\n")
    .filter((l) => l.trim() && !l.startsWith("#"))
    .map((l) => l.split("|"));

const cssName = (name) => "--" + name.replace(/\//g, "-").replace(/^background-/, "bg-");
const alias = (v) => (v.startsWith("{") ? `var(${cssName(v.slice(1, -1))})` : v);

const ref = parse("ref.txt");
const ui = parse("ui.txt");
const semantic = parse("semantic.txt");
const scale = parse("scale.txt");
const effects = ["effects.txt", "motion.txt", "opacity.txt", "layout.txt"].flatMap(parse);
const inline = (v) => v.replace(/\{([^}]+)\}/g, (_, n) => `var(${cssName(n)})`);

const brands = ["cobalt", "sunset", "olive", "bp-legacy"];
const block = (selector, lines) => `${selector} {\n${lines.map((l) => "  " + l).join("\n")}\n}\n`;

let prim = "/* GENERATED by scripts/build-tokens.mjs. Primitives: ref palette, ui scheme layer, scale. */\n\n";
prim += "/* Brand palette. Default brand: cobalt. */\n";
prim += block(":root", ref.map(([n, v]) => `${cssName(n)}: ${alias(v)};`));
brands.slice(1).forEach((b, i) => {
  prim += block(`[data-brand="${b}"]`, ref.map(([n, ...vals]) => `${cssName(n)}: ${alias(vals[i + 1])};`));
});
prim += "\n/* Scheme layer. Light is default, dark via [data-theme=dark]. */\n";
prim += block(":root, [data-theme=\"light\"]", ui.map(([n, l]) => `${cssName(n)}: ${alias(l)};`));
prim += block("[data-theme=\"dark\"]", ui.map(([n, , d]) => `${cssName(n)}: ${alias(d)};`));
prim += "\n/* Scale (default density). */\n";
prim += block(":root", scale.map(([n, v]) => `${cssName(n)}: ${/^(font-weight|line-height|letter-spacing)/.test(n) ? v : v + "px"};`));

prim += "\n/* Effects, motion, opacity, grid and layout. */\n";
prim += block(":root", effects.map(([n, v]) => `${cssName(n)}: ${inline(v)};`));

let sem = "/* GENERATED by scripts/build-tokens.mjs. Semantic roles. Components use ONLY these. */\n\n";
sem += block(":root, [data-theme=\"light\"]", [
  "--font-sans: var(--font-inter), \"Inter\", system-ui, sans-serif;",
  "--font-mono: var(--font-roboto-mono), \"Roboto Mono\", ui-monospace, monospace;",
  ...semantic.map(([n, l]) => `${cssName(n)}: ${alias(l)};`),
]);
sem += block("[data-theme=\"dark\"]", semantic.map(([n, , d]) => `${cssName(n)}: ${alias(d)};`));

writeFileSync(out("primitives.css"), prim);
writeFileSync(out("semantic.css"), sem);
console.log(`ref ${ref.length}, ui ${ui.length}, semantic ${semantic.length}, scale ${scale.length}, effects ${effects.length}`);
